# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

matches:
  - trigger: ";gh"
    replace: "https://github.com/davidsroth"

  - trigger: ";git"
    replace: "https://github.com/davidsroth"

  - trigger: ";mysite"
    replace: "https://www.davidroth.me/"

  - trigger: ";li"
    replace: "https://www.linkedin.com/in/david-s-roth/"

  - trigger: ";@@"
    replace: "davidsamuelroth@gmail.com"

  - trigger: ";##"
    replace: "2016153785"

  - trigger: ";addr"
    replace: "715 Saint Marks Avenue"

  # Print the current date
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"
  - trigger: ";dtime"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S%z"
  - trigger: ";uuid"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "head -c6 /dev/urandom | base64 | tr -d '\n='"
