customCommands:
  - key: 'F'
    command: 'git fetch --prune'
    context: 'localBranches'
    stream: true

gui:
  # If true, do not show a warning when discarding changes in the staging view.
  skipDiscardChangeWarning: true