customCommands:
  - key: "F"
    command: "git fetch --prune"
    context: "localBranches"
    output: log
gui:
  # If true, do not show a warning when discarding changes in the staging view.
  skipDiscardChangeWarning: true
