#!/usr/bin/env python3
"""Generate `US-NoOption.keylayout`.

A standard U.S. ANSI keyboard layout with the Option (Alt) modifier plane
stripped: Option no longer composes glyphs (ç/ƒ/µ ...) or arms dead-key
accents (´`¨ˆ˜ via ⌥e/⌥i/⌥u/⌥n/⌥`). Option becomes a pure modifier
system-wide, so Hammerspoon/Karabiner can use ⌥<key> hotkeys without the
keystroke leaking a character, and no per-key dead-key bypass is needed.

Run `./gen-us-nooption.py` to regenerate `US-NoOption.keylayout` in place.
The committed .keylayout is the artifact the bootstrap installs; this
generator exists so the layout is reproducible / reviewable.
"""
from __future__ import annotations

import pathlib
from xml.sax.saxutils import escape

# Stable identifiers. The negative `id` avoids collision with system layouts
# and is referenced by the bootstrap when it writes the HIToolbox pref, so it
# must stay fixed.
KEYBOARD_ID = -19341
KEYBOARD_NAME = "US-NoOption"
KEYBOARD_GROUP = 126  # Roman

# code -> unshifted output for a U.S. ANSI keyboard (Mac virtual key codes).
BASE: dict[int, str] = {
    0: "a", 1: "s", 2: "d", 3: "f", 4: "h", 5: "g", 6: "z", 7: "x", 8: "c",
    9: "v", 10: "\u00a7", 11: "b", 12: "q", 13: "w", 14: "e", 15: "r",
    16: "y", 17: "t",
    18: "1", 19: "2", 20: "3", 21: "4", 22: "6", 23: "5", 24: "=", 25: "9",
    26: "7", 27: "-", 28: "8", 29: "0",
    30: "]", 31: "o", 32: "u", 33: "[", 34: "i", 35: "p",
    36: "\r", 37: "l", 38: "j", 39: "'", 40: "k", 41: ";", 42: "\\",
    43: ",", 44: "/", 45: "n", 46: "m", 47: ".",
    48: "\t", 49: " ", 50: "`", 51: "\b", 53: "\x1b",
    # keypad (do not change with shift)
    65: ".", 67: "*", 69: "+", 75: "/", 76: "\r", 78: "-", 81: "=",
    82: "0", 83: "1", 84: "2", 85: "3", 86: "4", 87: "5", 88: "6",
    89: "7", 91: "8", 92: "9",
}

# Shift overrides for the non-letter keys (letters are just upper-cased).
SHIFT_SYMBOL: dict[int, str] = {
    10: "\u00b1", 18: "!", 19: "@", 20: "#", 21: "$", 22: "^", 23: "%",
    24: "+", 25: "(", 26: "&", 27: "_", 28: "*", 29: ")", 30: "}", 33: "{",
    39: '"', 41: ":", 42: "|", 43: "<", 44: "?", 47: ">", 50: "~",
}

# Control characters that XML 1.0 forbids as literals; emit as numeric refs
# (matching Apple's own .keylayout files, which macOS parses fine).
CTRL_REFS = {"\r": "&#x000D;", "\t": "&#x0009;", "\b": "&#x0008;", "\x1b": "&#x001B;"}


def out_attr(ch: str) -> str:
    if ch in CTRL_REFS:
        return CTRL_REFS[ch]
    return escape(ch).replace('"', "&#x0022;")


def shift_char(code: int, ch: str) -> str:
    if ch.isalpha():
        return ch.upper()
    return SHIFT_SYMBOL.get(code, ch)


def caps_char(ch: str) -> str:
    # Caps lock: upper-case letters only; symbols/digits stay unshifted.
    return ch.upper() if ch.isalpha() else ch


def key_map(index: int, mapping: dict[int, str]) -> str:
    lines = [f'    <keyMap index="{index}">']
    for code in sorted(mapping):
        lines.append(f'      <key code="{code}" output="{out_attr(mapping[code])}"/>')
    lines.append("    </keyMap>")
    return "\n".join(lines)


def main() -> None:
    base = BASE
    shift = {c: shift_char(c, ch) for c, ch in base.items()}
    caps = {c: caps_char(ch) for c, ch in base.items()}

    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE keyboard SYSTEM "file://localhost/System/Library/DTDs/KeyboardLayout.dtd">
<!-- Generated by gen-us-nooption.py - do not edit by hand. -->
<keyboard group="{KEYBOARD_GROUP}" id="{KEYBOARD_ID}" name="{KEYBOARD_NAME}" maxout="1">
  <layouts>
    <layout first="0" last="255" mapSet="ANSI" modifiers="Modifiers"/>
  </layouts>
  <modifierMap id="Modifiers" defaultIndex="0">
    <!-- 0: base. Option (with or without command) folds here -> no glyph layer. -->
    <keyMapSelect mapIndex="0">
      <modifier keys=""/>
      <modifier keys="anyOption"/>
      <modifier keys="command"/>
      <modifier keys="anyOption command"/>
    </keyMapSelect>
    <!-- 1: shift. Shift+Option folds here too. -->
    <keyMapSelect mapIndex="1">
      <modifier keys="anyShift"/>
      <modifier keys="anyShift anyOption"/>
      <modifier keys="anyShift command"/>
      <modifier keys="anyShift anyOption command"/>
      <modifier keys="caps anyShift"/>
    </keyMapSelect>
    <!-- 2: caps lock (upper-case letters, base symbols). -->
    <keyMapSelect mapIndex="2">
      <modifier keys="caps"/>
      <modifier keys="caps anyOption"/>
      <modifier keys="caps command"/>
    </keyMapSelect>
  </modifierMap>
  <keyMapSet id="ANSI">
{key_map(0, base)}
{key_map(1, shift)}
{key_map(2, caps)}
  </keyMapSet>
</keyboard>
"""
    dest = pathlib.Path(__file__).with_name("US-NoOption.keylayout")
    dest.write_text(xml, encoding="utf-8")
    print(f"wrote {dest} ({len(base)} keys x 3 maps)")


if __name__ == "__main__":
    main()
